version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    env_file:
      - ./server/.env
    volumes:
      - ./server/logs:/app/logs
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    depends_on:
      - client
      - server
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/build:/usr/share/nginx/html

volumes:
  db_data: